# Licensed under the Apache License, Version 2.0 or the MIT License.
# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright Tock Contributors 2023.

# This workflow contains the litex-ci-runner job, which uses the LiteX Verilated
# simulation to run a Tock kernel and perform various tests using libtock-c
# example applications.

name: test-workflow

on:
  push:

jobs:
  first-job:
    strategy:
      matrix:
        os: [ubuntu-latest]

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    steps:
      # Checkout the Tock repo, needs to happen at the beginning given
      # that other steps (such as the Rust toolchain) depend on files
      # in this repo.
      - name: Checkout the current repository
        uses: actions/checkout@v3

      - name: Print hello world
        run: |
          echo "Hello World"

  second-job:
    needs: first-job

    strategy:
      matrix:
        os: [ubuntu-latest]

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    steps:
      - name: Print hello world 2
        run: |
          echo "Hello World 2"
